const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');
const fs = require('fs');
const path = require('path');
const baseUrl = process.env.FXLAB_BASE_URL || 'http://192.168.88.5:8088';
(async () => {
  const browser = await chromium.launch({headless:true});
  const out = path.resolve(process.argv[2] || 'data/qa');
  fs.mkdirSync(out,{recursive:true});
  const errors=[];
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(baseUrl,{waitUntil:'networkidle'});
  await page.locator('#chart-status').filter({hasText:'наблюдений'}).waitFor();
  await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
  const initial=await page.locator('#chart-status').textContent();
  await page.selectOption('#period','90');
  const filtered=await page.locator('#chart-status').textContent();
  if(initial===filtered) throw Error('Period filter did not change chart');
  await page.locator('summary').click();
  if(await page.locator('#values tr').count()!==10) throw Error('Missing accessible table');
  for(const kind of ['h1','ecb','d1']) {
    await page.selectOption('#series',kind);
    await page.locator('#chart-status').filter({hasText:'наблюдений'}).waitFor();
    const description=await page.locator('#series-description').textContent();
    if(await page.locator('#chart').getAttribute('aria-label')!==description) throw Error('Wrong accessible chart identity for '+kind);
    if(await page.locator('#chart title').textContent()!==description) throw Error('Wrong SVG title for '+kind);
    if(await page.locator('#values tr').count()!==10) throw Error('Missing table for '+kind);
  }
  for(const report of ['decisions','questions','sources','deployment','denn','market-quality','macro-data','positioning','policy-events','event-alignment','baseline-experiments','causal-graph','interaction-experiments','readiness-review','acquisition-review','data-coverage','denn-baseline','denn-spectral','denn-spectral-stability']) {
    const response=await page.request.get(baseUrl+'/reports/'+report);
    if(response.status()!==200) throw Error('Report '+report+' failed');
  }
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl,{waitUntil:'networkidle'});
  await page.locator('#chart-status').filter({hasText:'наблюдений'}).waitFor();
  const dimensions=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));
  if(dimensions.body>dimensions.viewport) throw Error('Mobile page overflow');
  await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
  await page.goto(baseUrl+'/reports/market-quality',{waitUntil:'networkidle'});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Quality mobile overflow');
  await page.screenshot({path:path.join(out,'quality-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'quality-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/macro-data',{waitUntil:'networkidle'});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Macro report mobile overflow');
  await page.screenshot({path:path.join(out,'macro-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'macro-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/positioning',{waitUntil:'networkidle'});
  await page.locator('#positioning-status').filter({hasText:'отчётов'}).waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Positioning mobile overflow');
  await page.screenshot({path:path.join(out,'positioning-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'positioning-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/policy-events',{waitUntil:'networkidle'});
  await page.locator('#policy-status').filter({hasText:'решений'}).waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Policy mobile overflow');
  await page.screenshot({path:path.join(out,'policy-mobile.png'),fullPage:true});
  await page.locator('#policy-source').selectOption('ecb');
  await page.locator('#policy-status').filter({hasText:'ECB'}).waitFor();
  if(await page.locator('#policy-chart title').textContent()!=='Ставки ECB') throw Error('Wrong ECB chart title');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'policy-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/event-alignment',{waitUntil:'networkidle'});
  await page.getByText('267 строк из 193 событий').waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Alignment mobile overflow');
  await page.screenshot({path:path.join(out,'alignment-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'alignment-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/baseline-experiments',{waitUntil:'networkidle'});
  await page.getByText('Это не репликация surprise-эффекта').waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Experiments mobile overflow');
  await page.screenshot({path:path.join(out,'experiments-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'experiments-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/causal-graph',{waitUntil:'networkidle'});
  await page.locator('#graph-status').filter({hasText:'18 узлов'}).waitFor();
  await page.locator('#graph-chain').selectOption('cpi_us');
  await page.locator('#graph-status').filter({hasText:'7 узлов'}).waitFor();
  if(await page.locator('#graph-title').count()!==1 || await page.locator('#graph-desc').count()!==1) throw Error('Graph accessible name missing after redraw');
  if(await page.locator('#graph-node-controls button').count()!==7) throw Error('Accessible graph node controls missing');
  await page.locator('.graph-node').first().focus();
  await page.keyboard.press('Enter');
  if(!await page.locator('#graph-detail').getByText('available_non_strict').count()) throw Error('Graph node detail missing');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Graph mobile overflow');
  await page.screenshot({path:path.join(out,'graph-mobile.png'),fullPage:true});
  await page.locator('#graph-chain').selectOption('all');
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#graph-status').filter({hasText:'18 узлов'}).waitFor();
  await page.screenshot({path:path.join(out,'graph-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/interaction-experiments',{waitUntil:'networkidle'});
  await page.getByText('Это описательные non-strict срезы').waitFor();
  const interactionAll=await page.locator('#interaction-status').textContent();
  await page.locator('#interaction-feature').selectOption('positioning_regime');
  const interactionFiltered=await page.locator('#interaction-status').textContent();
  if(interactionAll===interactionFiltered) throw Error('Interaction filter did not change result count');
  await page.locator('#interaction-next').click();
  const interactionNext=await page.locator('#interaction-status').textContent();
  if(interactionNext===interactionFiltered) throw Error('Interaction pagination did not advance');
  if(await page.locator('.interaction-table tbody tr:visible').count()>12) throw Error('Interaction pagination shows too many rows');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Interactions mobile overflow');
  await page.screenshot({path:path.join(out,'interactions-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'interactions-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/readiness-review',{waitUntil:'networkidle'});
  await page.getByText('Доказан сквозным запуском').waitFor();
  await page.getByText('Заблокировано PIT-данными').waitFor();
  if(await page.locator('.milestone-list article').count()!==8) throw Error('Readiness milestone count mismatch');
  if(await page.locator('.readiness-table tbody tr').count()!==5) throw Error('Readiness priority count mismatch');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Readiness mobile overflow');
  await page.screenshot({path:path.join(out,'readiness-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'readiness-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/acquisition-review',{waitUntil:'networkidle'});
  await page.getByText('Готов к non-strict пилоту').waitFor();
  await page.getByText('Optional · paused').waitFor();
  if(await page.locator('.vendor-list article').count()!==4) throw Error('Consensus candidate count mismatch');
  if(await page.locator('.acceptance-list li').count()!==7) throw Error('Acceptance contract count mismatch');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Acquisition mobile overflow');
  await page.screenshot({path:path.join(out,'acquisition-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'acquisition-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/data-coverage',{waitUntil:'networkidle'});
  await page.getByText('COMMON OVERLAP').waitFor();
  if(await page.locator('.coverage-table tbody tr').count()<8) throw Error('Open-data coverage rows missing');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Coverage mobile overflow');
  await page.screenshot({path:path.join(out,'coverage-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'coverage-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/denn-baseline',{waitUntil:'networkidle'});
  await page.getByText('Graph training ещё не используется.').waitFor();
  if(await page.locator('.denn-table tbody tr').count()!==4) throw Error('DENN horizon count mismatch');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('DENN mobile overflow');
  await page.screenshot({path:path.join(out,'denn-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'denn-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/denn-spectral',{waitUntil:'networkidle'});
  await page.getByText('Full-sample descriptive analysis.').waitFor();
  if(await page.locator('.spectral-table tbody tr').count()!==25) throw Error('Spectral band count mismatch');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Spectral mobile overflow');
  await page.screenshot({path:path.join(out,'spectral-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'spectral-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseUrl+'/reports/denn-spectral-stability',{waitUntil:'networkidle'});
  await page.getByText('Chronological descriptive diagnostic.').waitFor();
  if(await page.locator('#bands tbody tr').count()!==10) throw Error('Spectral stability leader count mismatch');
  if(await page.locator('#lags tbody tr').count()!==10) throw Error('Spectral lag-one count mismatch');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Spectral stability mobile overflow');
  await page.screenshot({path:path.join(out,'spectral-stability-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'spectral-stability-desktop.png'),fullPage:true});
  if(errors.length) throw Error(errors.join('\n'));
  console.log(JSON.stringify({initial,filtered,dimensions,interactionAll,interactionFiltered,errors,screenshots:out}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
