const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');
const fs = require('fs');
const path = require('path');
(async () => {
  const browser = await chromium.launch({headless:true});
  const out = path.resolve(process.argv[2] || 'data/qa');
  fs.mkdirSync(out,{recursive:true});
  const errors=[];
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://192.168.88.5:8088',{waitUntil:'networkidle'});
  await page.locator('#chart-status').filter({hasText:'наблюдений'}).waitFor();
  await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
  const initial=await page.locator('#chart-status').textContent();
  await page.selectOption('#period','90');
  const filtered=await page.locator('#chart-status').textContent();
  if(initial===filtered) throw Error('Period filter did not change chart');
  await page.locator('summary').click();
  if(await page.locator('#values tr').count()!==10) throw Error('Missing accessible table');
  for(const kind of ['h1','ecb','d1']) {
    await page.selectOption('#series',kind);
    await page.locator('#chart-status').filter({hasText:'наблюдений'}).waitFor();
    const description=await page.locator('#series-description').textContent();
    if(await page.locator('#chart').getAttribute('aria-label')!==description) throw Error('Wrong accessible chart identity for '+kind);
    if(await page.locator('#chart title').textContent()!==description) throw Error('Wrong SVG title for '+kind);
    if(await page.locator('#values tr').count()!==10) throw Error('Missing table for '+kind);
  }
  for(const report of ['decisions','questions','sources','deployment','market-quality','macro-data','positioning','policy-events','event-alignment','baseline-experiments']) {
    const response=await page.request.get('http://192.168.88.5:8088/reports/'+report);
    if(response.status()!==200) throw Error('Report '+report+' failed');
  }
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://192.168.88.5:8088',{waitUntil:'networkidle'});
  await page.locator('#chart-status').filter({hasText:'наблюдений'}).waitFor();
  const dimensions=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));
  if(dimensions.body>dimensions.viewport) throw Error('Mobile page overflow');
  await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
  await page.goto('http://192.168.88.5:8088/reports/market-quality',{waitUntil:'networkidle'});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Quality mobile overflow');
  await page.screenshot({path:path.join(out,'quality-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'quality-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://192.168.88.5:8088/reports/macro-data',{waitUntil:'networkidle'});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Macro report mobile overflow');
  await page.screenshot({path:path.join(out,'macro-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'macro-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://192.168.88.5:8088/reports/positioning',{waitUntil:'networkidle'});
  await page.locator('#positioning-status').filter({hasText:'отчётов'}).waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Positioning mobile overflow');
  await page.screenshot({path:path.join(out,'positioning-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'positioning-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://192.168.88.5:8088/reports/policy-events',{waitUntil:'networkidle'});
  await page.locator('#policy-status').filter({hasText:'решений'}).waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Policy mobile overflow');
  await page.screenshot({path:path.join(out,'policy-mobile.png'),fullPage:true});
  await page.locator('#policy-source').selectOption('ecb');
  await page.locator('#policy-status').filter({hasText:'ECB'}).waitFor();
  if(await page.locator('#policy-chart title').textContent()!=='Ставки ECB') throw Error('Wrong ECB chart title');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'policy-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://192.168.88.5:8088/reports/event-alignment',{waitUntil:'networkidle'});
  await page.getByText('267 строк из 193 событий').waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Alignment mobile overflow');
  await page.screenshot({path:path.join(out,'alignment-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'alignment-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://192.168.88.5:8088/reports/baseline-experiments',{waitUntil:'networkidle'});
  await page.getByText('Это не репликация surprise-эффекта').waitFor();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Experiments mobile overflow');
  await page.screenshot({path:path.join(out,'experiments-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(out,'experiments-desktop.png'),fullPage:true});
  if(errors.length) throw Error(errors.join('\n'));
  console.log(JSON.stringify({initial,filtered,dimensions,errors,screenshots:out}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
